### ISSUE TITLE
Port benchmarks to Pharo/Squeak

### ISSUE THREAD

**Issue by smarr** [smarr/are-we-fast-yet#14]
Port all benchmarks to Pharo/Squeak and add them to setup.

Consider using the [AweSOM](http://smalltalkhub.com/#!/~StefanMarr/AweSOM) SOM parser as foundation, adapt it to load classes and methods into Squeak/Pharo.
That way, we might be able to avoid having multiple copies of the benchmarks. Or, at least have them in a format that is easily kept in sync.

/cc @charig, might be relevant for you. But haven't started with it yet.

**Comment by charig** [comment]
Yes, it would be interesting for me to have. Let me know if i can help.

**Comment by smarr** [comment]
Pharo support is now in the repo: https://github.com/smarr/are-we-fast-yet/compare/f2df74fa8fb8bbd783732e53a2a53284d45c0032...fb67c7f5628dfde2ac73b46494986f042d2abbe2
