### ISSUE TITLE
Port benchmarks to Python

### ISSUE THREAD

**Issue by smarr** [smarr/are-we-fast-yet#4]
Port all benchmarks to Python 2.x and add PyPy and CPython to setup.

**Comment by q3cpma** [comment]
Was PyPy ever included? What about the god-knows-how-many alternative Python implementations like Pyston, Cinder, Nuitka, Numba, etc...?

**Comment by smarr** [comment]
I do have number for PyPy and CPython:
https://stefan-marr.de/downloads/tmp/awfy-graal-dyn-lang-22.2.html

Though, I have not spent the time to setup things beyond those two.

I'll close the issue since we do have Python versions of the benchmarks as per #50.
